export const ACTIONS = {
  BOOTSTRAP_APP: 'BOOTSTRAP_APP',
  FINISH_BOOTSTRAP: 'FINISH_BOOTSTRAP',

  CLEAR_SUCCESS_BY_ACTION_TYPE: 'CLEAR_SUCCESS_BY_ACTION_TYPE',
  CLEAR_ERROR_BY_ACTION_TYPE: 'CLEAR_ERROR_BY_ACTION_TYPE',

  REGISTER_DOCTOR_REQUEST: 'REGISTER_DOCTOR_REQUEST',
  REGISTER_DOCTOR_SUCCESS: 'REGISTER_DOCTOR_SUCCESS',
  REGISTER_DOCTOR_FAILURE: 'REGISTER_DOCTOR_FAILURE',

  REGISTER_PATIENT_REQUEST: 'REGISTER_PATIENT_REQUEST',
  REGISTER_PATIENT_SUCCESS: 'REGISTER_PATIENT_SUCCESS',
  REGISTER_PATIENT_FAILURE: 'REGISTER_PATIENT_FAILURE',

  AUTHORIZE_USER: 'AUTHORIZE_USER',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT: 'LOGOUT',

  SET_APP_SERVER_ERROR: 'SET_APP_SERVER_ERROR',
  CLEAR_INTERNAL_ERROR: 'CLEAR_INTERNAL_ERROR',
};

export const ERRORS: { [key: string]: string } = {
  'The email already exists.': 'Пользователь с таким email уже зарегистрирован',
};
